version: '3.1'
services:
  stats-server:
    build: ./stats-service/stats-server
    container_name: stats-server
    depends_on:
      - stats-db
    ports:
      - "9090:9090"
    environment:
      - DB_NAME=stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_HOST=stats-db
      - DB_PORT=5432
      - STATS_SERVICE_URL=http://stats-server:9090

  stats-db:
    image: postgres:14-alpine
    container_name: statsDB
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_HOST=stats-db
      - DB_PORT=5432

  ewm-service:
    build: ./ewm-serv
    container_name: ewm-service
    depends_on:
      - stats-server
      - ewm-db
    ports:
      - "8080:8080"
    environment:
      - STATS_SERVICE_URL=http://stats-server:9090
      - DB_NAME=ewm
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_HOST=ewm-db
      - DB_PORT=5432

  ewm-db:
    image: postgres:14-alpine
    container_name: ewmDB
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_HOST=ewm-db
      - DB_PORT=5432
